package com.bepa.eis.common.enums.project;

public enum ClassificationType {

    CLASS_A_(
            1,
            "A_",
            "Cover all A codes - Software Control",
            "Software controlled interfaces",
            "UI, GUI, API, USB, REST, TCP",
            true),
    CLASS_AA(
            2,
            "AA",
            "User Interfaces (UI)",
            "GUI, Command-Line (CLI), menu-driven, touch, voice, gestures",
            "",
            true),
    CLASS_AB(
            3,
            "AB",
            "Software-to-Software interfaces",
            "APIs, SDK, Libraries, Function/procedure calls",
            "",
            true),
    CLASS_AC(
            4,
            "AC",
            "System Interfaces",
            "Interfaces between software and operation systems (eg. Backbones), databases, file systems, or external systems",
            "",
            true),
    CLASS_AD(
            5,
            "AD",
            "Hardware Interfaces",
            "Software interaction with sensors, actuators, controllers, USB/serial devices etc.",
            "",
            true),
    CLASS_AE(
            6,
            "AE",
            "Communication Interfaces",
            "REST, SOAP, WebSockets, TCP/IP, messaging queues, RPC",
            "",
            true),
    CLASS_AF(
            7,
            "AF",
            "Data Interfaces",
            "Files, databases, shared memory, datastreams, import/export formats",
            "",
            true),
    CLASS_AG(
            8,
            "AG",
            "Control Interfaces",
            "Interfaces used to issue commands, change operating modes, configure parameters, or start/stop processes",
            "",
            true),
    CLASS_AH(
            9,
            "AH",
            "Monitoring/Diagnostic Interfaces",
            "Interfaces providing status, logs, alarms, health information, and diagnostic data",
            "",
            true),
    CLASS_AI(
            10,
            "AI",
            "Security Interfaces",
            "Authentication, authorization, encryption/key-management, and access-control interfaces",
            "",
            true),
    CLASS_B_(
            11,
            "B_",
            "Cover all B codes - Converting an input variable (physical property, condition or event) into a signal for further processing",
            "Detecting\nSensing\nRecording Measurements\nMonitoring",
            "Auxiliary switch (as position indicator)\nBuchholz relay\nCurrent transformer\nDifferential protection relays\nDistance protection relays\nFlame detector\nGas detector\nLimit switch\nMeasuring element\nMeasuring relay\nMeasuring shunt (resistance)\nMicrophone\nDetector\nMovement detector\nOptical current transformer\nOptical voltage transformer\nOver-current protection relay\nOverload relay\nPhotocell\nPosition switch\nProtection relay\nProtection cubicle\nProximity sensor\nProximity switch\nSafety cabinet\nSensor\nSmoke sensor\nTemperature sensor\nVideo camera\nVoltage transformer",
            true),
    CLASS_BA(
            12,
            "BA",
            "Electrical potential",
            "Measuring relay (voltage), measuring shunt (voltage), measuring transformer (voltage), protection relay (voltage), voltage transformer",
            "",
            true),
    CLASS_BB(
            13,
            "BB",
            "Electrical current",
            "Current transformer, measuring relay (current), measuring transformer (current), protection relay (current), overload relay (current) (Shunt)",
            "",
            true),
    CLASS_BC(
            14,
            "BC",
            "Density",
            "",
            "",
            true),
    CLASS_BD(
            15,
            "BD",
            "Other electrical or electromagnetic variable",
            "Measuring relay, measuring shunt (resistance), measuring transformer, protection relay",
            "",
            true),
    CLASS_BE(
            16,
            "BE",
            "Flow",
            "Flow meter, gas meter, water meter",
            "",
            true),
    CLASS_BF(
            17,
            "BF",
            "Gauge, position, length (including distance, elongation, amplitude)",
            "Motion sensor, movement detector, position switch, proximity switch, proximity sensor",
            "",
            true),
    CLASS_BG(
            18,
            "BG",
            "Power",
            "",
            "",
            true),
    CLASS_BH(
            19,
            "BH",
            "Time",
            "Clock, time counter",
            "",
            true),
    CLASS_BJ(
            20,
            "BJ",
            "Level",
            "Level sensor",
            "",
            true),
    CLASS_BK(
            21,
            "BK",
            "Moisture, Humidity",
            "Humidity meter",
            "",
            true),
    CLASS_BL(
            22,
            "BL",
            "Pressure, Vacuum",
            "Pressure gauge, pressure sensor",
            "",
            true),
    CLASS_BM(
            23,
            "BM",
            "Quality (composition, concentration, purity, material property)",
            "Gas analyzer, x-ray machine",
            "",
            true),
    CLASS_BN(
            24,
            "BN",
            "Radiation",
            "Flame detector, smoke detector",
            "",
            true),
    CLASS_BO(
            25,
            "BO",
            "Speed, frequency (including acceleration)",
            "Accelerometer, speedometer, tachometer, vibration pickup",
            "",
            true),
    CLASS_BP(
            26,
            "BP",
            "Temperature",
            "Temperature sensor, temperature monitor",
            "",
            true),
    CLASS_BQ(
            27,
            "BQ",
            "Multi-variable",
            "Buchholz relay, protection cubicle",
            "",
            true),
    CLASS_BR(
            28,
            "BR",
            "Weight, Force",
            "Load cell",
            "",
            true),
    CLASS_BS(
            29,
            "BS",
            "Other quantities",
            "Microphone, video camera",
            "",
            true),
    CLASS_BT(
            30,
            "BT",
            "Number of events, counts, combined tasks",
            "Switching cycle detector, combined instrument transformer",
            "",
            true),
    CLASS_C_(
            31,
            "C_",
            "Cover all C codes - Storing of energy, information or material",
            "Recording  storage",
            "Buffer battery\nCapacitor\nEvent recorder (mainly for storage\npurposes)\nHard disk\nMagnetic tape recorder (mainly for storage purposes)\nMemory\nRAM\nStorage battery\nVideo recorder (mainly for storage purposes)\nVoltage recorder (mainly for storage purposes) Water tank",
            true),
    CLASS_CA(
            32,
            "CA",
            "Capacitive storage of electric energy",
            "Capacitor",
            "",
            true),
    CLASS_CB(
            33,
            "CB",
            "Inductive storage of electric energy",
            "Coil, Superconductor",
            "",
            true),
    CLASS_CC(
            34,
            "CC",
            "Chemical storage of electric energy",
            "Buffer battery NOTE Batteries seen as energy sources are assigned to main Class G",
            "",
            true),
    CLASS_CD(
            35,
            "CD",
            "Storage of information",
            "CD-ROM, EPROM, event recorder, hard disk, magnetic tape recorder, memory, RAM, video recorder, voltage recorder",
            "",
            true),
    CLASS_CE(
            36,
            "CE",
            "Open storage of material at fixed location (collection, housing)",
            "Bunker, cistern, paper reel stand, pit, pool",
            "",
            true),
    CLASS_CF(
            37,
            "CF",
            "Closed storage of material at fixed location (collection, housing)",
            "Accumulator, barrel, boiler, buffer, container, depository, flash tank, gas holder, safe, silo, tank",
            "",
            true),
    CLASS_CG(
            38,
            "CG",
            "Moveable storage of material (collection, housing)",
            "Container, transportation containers, gas cylinder, shipping container",
            "",
            true),
    CLASS_CH(
            39,
            "CH",
            "Storage of thermal energy",
            "Hot water accumulator, hybrid heat storage, ice tank, steam storage, thermal energy storage, underground thermal energy storage",
            "",
            true),
    CLASS_CI(
            40,
            "CI",
            "Storage of mechanical energy",
            "Flywheel, rubber band",
            "",
            true),
    CLASS_CJ(
            41,
            "CJ",
            "Free to use",
            "",
            "",
            true),
    CLASS_D_(
            42,
            "D_",
            "Cover all D codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_DA(
            43,
            "DA",
            "Free to use",
            "",
            "",
            true),
    CLASS_DB(
            44,
            "DB",
            "Free to use",
            "",
            "",
            true),
    CLASS_E_(
            45,
            "E_",
            "Cover all E codes - Supply of radiant or thermal energy",
            "Cooling\nHeating\nLighting\nRadiating",
            "Boiler\nElectrical heater\nHeater\nLamp\nLaser\nLuminaire",
            true),
    CLASS_EA(
            46,
            "EA",
            "Free to use",
            "",
            "",
            true),
    CLASS_EB(
            47,
            "EB",
            "Free to use",
            "",
            "",
            true),
    CLASS_F_(
            48,
            "F_",
            "Cover all F codes - Direct protection (self-acting) of a flow of energy, signals, personnel or equipment from dangerous or unwanted conditions Including systems and equipment for protective purposes Protection devices see code B.",
            "Absorbing\nGuarding\nPreventing\nProtecting\nSecuring\nShielding",
            "Fuse\nGuard\nMiniature circuit-breaker\nOil extension vessel\nOvervoltage limiter\nRupture disc\nSafety valve\nShielding\nSurge arrester\nThermal overload release",
            true),
    CLASS_FA(
            49,
            "FA",
            "Protection against overvoltage",
            "Arrester, surge arrester",
            "",
            true),
    CLASS_FB(
            50,
            "FB",
            "Protection against residual current",
            "Residual current device",
            "",
            true),
    CLASS_FC(
            51,
            "FC",
            "Protection against overcurrent",
            "Fuse, fuse unit, miniature circuit-breaker, thermal overload release",
            "",
            true),
    CLASS_FD(
            52,
            "FD",
            "Protection against other electrical hazards",
            "Enclosure for electromagnetic shielding, Faraday cage",
            "",
            true),
    CLASS_FE(
            53,
            "FE",
            "Protection against hazardous pressure condition",
            "Automatic drains trap, rupture disc, safety valve, vacuum breaker",
            "",
            true),
    CLASS_FF(
            54,
            "FF",
            "Protection against effects of fire",
            "Fire damper, fire protection door, fire protection facility, lock",
            "",
            true),
    CLASS_FG(
            55,
            "FG",
            "Protection against hazardous operating condition or damage",
            "Impact protection, protection device, protective shield, protective sleeve for thermocouple, safety clutch",
            "",
            true),
    CLASS_FH(
            56,
            "FH",
            "Protection against hazardous emission (E.g. radiation, chemical emissions, noise)",
            "Reactor protection equipment",
            "",
            true),
    CLASS_FI(
            57,
            "FI",
            "Protection against hazards or unwanted situations for person or animals (e.g. safeguarding)",
            "Airbag, barriers, contact protection, escape door, escape window, fence, gates, glare protection, guard, vision protection, railing, safety belt",
            "",
            true),
    CLASS_FJ(
            58,
            "FJ",
            "Protection of mechanical and building technology products and systems against wear (e.g. corrosion)",
            "Cathodic protection anode",
            "",
            true),
    CLASS_FK(
            59,
            "FK",
            "Protection against environmental effects (e.g. weather, geophysical effects)",
            "Avalanche protection device, geophysical protection device, weather protection device",
            "",
            true),
    CLASS_G_(
            60,
            "G_",
            "Cover all G codes - Initiating a flow of energy or material or Generating signals used as information carriers or reference source",
            "Generating",
            "Dry cell battery\nFan\nFuel cell\nGenerator\nPump\nSignal generator\nSolar cell",
            true),
    CLASS_GA(
            61,
            "GA",
            "Initiation of an electrical energy flow by use of mechanical energy",
            "Dynamo, generator, motor-generator set, power generator, rotating generator",
            "",
            true),
    CLASS_GB(
            62,
            "GB",
            "Initiation of an electrical energy flow by chemical conversion",
            "Battery, dry cell battery, fuel cell",
            "",
            true),
    CLASS_GC(
            63,
            "GC",
            "Initiation of an electrical energy flow using light",
            "Solar cell",
            "",
            true),
    CLASS_GD(
            64,
            "GD",
            "Generation of signals as an information carrier",
            "Signal generator, transducer",
            "",
            true),
    CLASS_GE(
            65,
            "GE",
            "Initiation of a continuous flow of solid matter",
            "Belt, chain conveyor, distributor",
            "",
            true),
    CLASS_GF(
            66,
            "GF",
            "Initiation of a discontinuous flow of solid matter",
            "Crane, elevators, forklift, lifting gear, manipulator, lifting device",
            "",
            true),
    CLASS_GG(
            67,
            "GG",
            "Initiation of a flow of liquid or flowing substances driven by an energy supply",
            "Pump, screw conveyor",
            "",
            true),
    CLASS_GH(
            68,
            "GH",
            "Initiation of a flow of gaseous substances by a mechanical driver",
            "Aspirator, blower, compressor, fan, vacuum pump, ventilator",
            "",
            true),
    CLASS_GI(
            69,
            "GI",
            "Initiation of a flow of liquid or gaseous substances by driving medium",
            "Ejector, injector, jet",
            "",
            true),
    CLASS_GJ(
            70,
            "GJ",
            "Initiation of a flow of liquid or gaseous substances by gravity",
            "Lubricator, oiler",
            "",
            true),
    CLASS_H_(
            71,
            "H_",
            "Cover all H codes - Producing a new kind of material or product",
            "Assembling\nCrushing\nDisassembling\nFractionating\nMaterial removing\nMilling\nMixing\nProducing\nPulverizing",
            "Centrifuge\nMill\nMixer\nSeparator",
            true),
    CLASS_HA(
            72,
            "HA",
            "Generation of a new product by assembling",
            "Assembly robot, component insertion machine",
            "",
            true),
    CLASS_HB(
            73,
            "HB",
            "Separation of mixtures of substances by centrifugal force",
            "Centrifuge, cyclone device",
            "",
            true),
    CLASS_HC(
            74,
            "HC",
            "Separation of mixtures of substances by gravity",
            "Separator, settling tank, vibrator",
            "",
            true),
    CLASS_HD(
            75,
            "HD",
            "Separation of mixtures of substances by thermal processes",
            "Distillation column, drying (Munters air dryer), extraction system",
            "",
            true),
    CLASS_HE(
            76,
            "HE",
            "Separation of mixtures of substances by filtering or classification",
            "Fluid filter, gas filter, grate, rake, screen",
            "",
            true),
    CLASS_HF(
            77,
            "HF",
            "Separation of mixtures of substances by electrostatic or magnetic forces",
            "Electrostatic precipitator, magnetic separator",
            "",
            true),
    CLASS_HG(
            78,
            "HG",
            "Separation of mixtures of substances by physical processes",
            "Absorption washer, active charcoal absorber, ion exchanger, wet ash scrubber",
            "",
            true),
    CLASS_HH(
            79,
            "HH",
            "Generation of new gaseous substances",
            "Gasifier",
            "",
            true),
    CLASS_HI(
            80,
            "HI",
            "Generation of new form of solid material by crushing",
            "Crusher, mill",
            "",
            true),
    CLASS_HJ(
            81,
            "HJ",
            "Generation of new form of solid material by coarsening",
            "Briquette maker, pellet maker, sintering facility, tablet maker",
            "",
            true),
    CLASS_HK(
            82,
            "HK",
            "Generation of new substances by mixing",
            "Emulsifier, humidifier (steam), kneader, mixer, mixing vessel, static mixer, stirrer",
            "",
            true),
    CLASS_HL(
            83,
            "HL",
            "Generation of new substances by chemical reaction",
            "Reaction furnace, reactor",
            "",
            true),
    CLASS_HM(
            84,
            "HM",
            "Generation of new substances by biological reaction",
            "Composter, fermenter",
            "",
            true),
    CLASS_I_(
            85,
            "I_",
            "Cover all I codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_IA(
            86,
            "IA",
            "Free to use",
            "",
            "",
            true),
    CLASS_IB(
            87,
            "IB",
            "Free to use",
            "",
            "",
            true),
    CLASS_J_(
            88,
            "J_",
            "Cover all J codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_JA(
            89,
            "JA",
            "Free to use",
            "",
            "",
            true),
    CLASS_JB(
            90,
            "JB",
            "Free to use",
            "",
            "",
            true),
    CLASS_K_(
            91,
            "K_",
            "Cover all K codes - Processing (receiving, treating and providing) signals or information (excluding objects for protective purposes, see Class B or F)",
            "Closing (of control circuits)\nContinuous controlling\nDelaying\nOpening (of control circuits)\nSwitching (of control circuits)\nSynchronizing",
            "All-or-nothing relay\nAutomation device\nAuxiliary relay\nBlocking device\nComputer\nContactor relay\nControl device\nControl panel\nControl valve\nController\nCPU\nDelay device\nField control device\nFilter\nFilter\nInterlocking device\nOptical coupler\nSwitching fault protection device\nSynchronizing device\nTime relay\nTransistor\nTrip relay\nVoltage controller",
            true),
    CLASS_KA(
            92,
            "KA",
            "Processing of electrical and electronic signals",
            "All-or-nothing relay, analogue integrated circuit, automatic paralleling device, binary elements, binary integrated circuit, contactor relay, CPU, delay element, delay line, electronic valve, electronic tube, feedback controller, filter (AC or DC), induction stirrer, input/output module, microprocessor, opto-coupler, process computer, programmable controller, receiver, safety logic module, synchronizing device, time relay, transistor, transmitter",
            "",
            true),
    CLASS_KB(
            93,
            "KB",
            "Processing of optical and acoustical signals",
            "Mirror, controller, test unit",
            "",
            true),
    CLASS_KC(
            94,
            "KC",
            "Processing of fluid and pneumatic signals",
            "Controller (valve position controller), fluid feedback controller, pilot valve, valve assembly",
            "",
            true),
    CLASS_KD(
            95,
            "KD",
            "Processing of mechanical signals",
            "Controller, linkage",
            "",
            true),
    CLASS_KE(
            96,
            "KE",
            "Processing of various input/output information carriers (e.g. electrical/pneumatic)",
            "Controller, electro-hydraulic converter, electric pilot valve",
            "",
            true),
    CLASS_L_(
            97,
            "L_",
            "Cover all L codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_LA(
            98,
            "LA",
            "Free to use",
            "",
            "",
            true),
    CLASS_LB(
            99,
            "LB",
            "Free to use",
            "",
            "",
            true),
    CLASS_M_(
            100,
            "M_",
            "Cover all M codes - Providing mechanical energy (rotational or linear mechanical motion) for driving purposes",
            "Actuating Driving",
            "Actuating coil\nActuator\nElectric motor Linear motor",
            true),
    CLASS_MA(
            101,
            "MA",
            "Driving by electromagnetic force",
            "Electric motor, linear motor",
            "",
            true),
    CLASS_MB(
            102,
            "MB",
            "Driving by magnetic force",
            "Actuating coil, actuator, electromagnet, magnetic drive",
            "",
            true),
    CLASS_MC(
            103,
            "MC",
            "Driving by mechanical force",
            "Friction wheel drive, mechanical actuator, spring force, stored-energy spring actuator, weight",
            "",
            true),
    CLASS_MD(
            104,
            "MD",
            "Driving by hydraulic or pneumatic force",
            "Fluid actuator, fluid cylinder, fluid motor, hydraulic cylinder, servomotor",
            "",
            true),
    CLASS_ME(
            105,
            "ME",
            "Driving by steam flow force",
            "Steam turbine",
            "",
            true),
    CLASS_MF(
            106,
            "MF",
            "Driving by gas flow force",
            "Gas turbine",
            "",
            true),
    CLASS_MG(
            107,
            "MG",
            "Driving by wind force",
            "Wind turbine",
            "",
            true),
    CLASS_MH(
            108,
            "MH",
            "Driving by fluid flow force",
            "Hydraulic turbine",
            "",
            true),
    CLASS_MI(
            109,
            "MI",
            "Driving by force using chemical conversion means",
            "Combustion engine",
            "",
            true),
    CLASS_N_(
            110,
            "N_",
            "Cover all N codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_NA(
            111,
            "NA",
            "Free to use",
            "",
            "",
            true),
    CLASS_NB(
            112,
            "NB",
            "Free to use",
            "",
            "",
            true),
    CLASS_O_(
            113,
            "O_",
            "Cover all O codes - Customer specific codes",
            "---",
            "---",
            true),
    CLASS_OA(
            114,
            "OA",
            "Free to use",
            "",
            "",
            true),
    CLASS_OB(
            115,
            "OB",
            "Free to use",
            "",
            "",
            true),
    CLASS_P_(
            116,
            "P_",
            "Cover all P codes - Presenting information",
            "Alarming\nCommunicating\nDisplaying\nIndicating\nInforming\nMeasuring (presentation of variables)\nPresenting\nPrinting\nWarning",
            "Bell\nClock\nCurrent measuring device\nEvent counter\nHorn\nIndicator\nLoudspeaker\nMechanical drop indicator relay\nMeter cabinet\nMonitor\nPower factor indicator\nPrinter\nReactive power meter\nSignal lamp\nStatus panel\nSwitching cycle counter\nSynchroscope\nText display\nTemperature gauge\nVoltmeter\nWatt-hour meter\nWattmeter",
            true),
    CLASS_PA(
            117,
            "PA",
            "Visible presentation of discrete states",
            "LED, mechanical drop indicator, signal lamp",
            "",
            true),
    CLASS_PB(
            118,
            "PB",
            "Visible presentation of values of discrete variables",
            "Ammeter, barometer, clock, counter, event counter, flow meter, frequency meter, Geiger counter, manometer, sight glass, synchroscope, thermometer, voltmeter, watt-hour meter, wattmeter, weight display",
            "",
            true),
    CLASS_PC(
            119,
            "PC",
            "Visible presentation of information in drawing, pictorial and/or textual form",
            "Analogue recorder, barcode printer, event recorder (mainly for presenting information), printer, recording voltmeter, text display, video screen",
            "",
            true),
    CLASS_PD(
            120,
            "PD",
            "Audible presentation of information",
            "Bell, horn, loudspeaker, whistle",
            "",
            true),
    CLASS_PE(
            121,
            "PE",
            "Tactile presentation of information",
            "Vibrator",
            "",
            true),
    CLASS_Q_(
            122,
            "Q_",
            "Cover all Q codes - Controlled switching or varying a flow of energy, of signals (for signals in control circuits, see Classes K and S) or of material",
            "Opening (of energy, signals and material flow)\nClosing (of energy, signals and material flow)\nSwitching (of energy, signals and material flow)\nClutching",
            "Circuit-breaker\nContactor (for power)\nDisconnector\nEarthing switch\nFuse switch (if main purpose is protection, see Class F)\nFuse-switch-disconnector (if main purpose is protection, see Class F)\nLoad-break switch\nMotor protection switch\nMotor starter\nPower transistor\nSwitchyard\nThyristor",
            true),
    CLASS_QA(
            123,
            "QA",
            "Switching and variation of electrical energy circuits",
            "Circuit-breaker, contactor, motor starter, power transistor, thyristor",
            "",
            true),
    CLASS_QB(
            124,
            "QB",
            "Isolation of electrical energy circuits",
            "Disconnector, fuse switch, fuse-switch disconnector, isolating switch, load-break switch",
            "",
            true),
    CLASS_QC(
            125,
            "QC",
            "Earthing of electrical energy circuits",
            "Earthing switch",
            "",
            true),
    CLASS_QD(
            126,
            "QD",
            "Braking",
            "Brake",
            "",
            true),
    CLASS_QE(
            127,
            "QE",
            "Switching of flow of liquid substances in closed enclosures",
            "Blank, blanking plate, damper, shutoff valve (including drain valve), solenoid valve",
            "",
            true),
    CLASS_QF(
            128,
            "QF",
            "Varying of flow of liquid substances in closed enclosure",
            "Control damper, control valve, gas control path",
            "",
            true),
    CLASS_QG(
            129,
            "QG",
            "Switching or varying of flow of liquid substances in open enclosures",
            "Dam plate, lock gate",
            "",
            true),
    CLASS_QH(
            130,
            "QH",
            "Providing access to an area",
            "Bar (lock), cover, door, gate, lock, turnstile, window",
            "",
            true),
    CLASS_QI(
            131,
            "QI",
            "Shut-off of flow of liquid substances (no valves)",
            "Isolation device, rotary lock (open/close)",
            "",
            true),
    CLASS_R_(
            132,
            "R_",
            "Cover all R codes - Restricting or stabilizing motion or a flow of energy, information or material",
            "Blocking\nDamping\nRestricting\nLimiting\nStabilizing",
            "Diode\nInductor\nLimiter\nResistor\nZener diode",
            true),
    CLASS_RA(
            133,
            "RA",
            "Limiting a flow of electrical energy",
            "Arc-suppressing reactor, diode, inductor, limiter, resistor",
            "",
            true),
    CLASS_RB(
            134,
            "RB",
            "Stabilizing a flow of electrical energy",
            "Uninterruptible power supply (UPS)",
            "",
            true),
    CLASS_RC(
            135,
            "RC",
            "Stabilizing a signal",
            "Equalizer, filter, low pass",
            "",
            true),
    CLASS_RD(
            136,
            "RD",
            "Restricting an unauthorized operation and/or movement (mechanical)",
            "Blocking device, latch, lock, stop",
            "",
            true),
    CLASS_RE(
            137,
            "RE",
            "Restricting a return flow of gaseous, liquid and flowing substances",
            "Check valve",
            "",
            true),
    CLASS_RF(
            138,
            "RF",
            "Restricting a flow of liquid and gaseous substances",
            "Flow restrictor, orifice plate, Venturi nozzle, water-proof seal",
            "",
            true),
    CLASS_RG(
            139,
            "RG",
            "Restricting an emission of sound",
            "Noise protection, sound absorber",
            "",
            true),
    CLASS_RH(
            140,
            "RH",
            "Restricting a thermal flow",
            "Insulation, jacket, lagging, lining, thermal insulation louver damper",
            "",
            true),
    CLASS_RI(
            141,
            "RI",
            "Restricting a mechanical effect",
            "Brick lining, compensator, shock absorber, vibration absorption",
            "",
            true),
    CLASS_RJ(
            142,
            "RJ",
            "Restricting a chemical effect",
            "Brick lining, explosion protection, gas penetration protection, splash protection",
            "",
            true),
    CLASS_RK(
            143,
            "RK",
            "Restricting an emission of   light",
            "Blind, screen, shutter",
            "",
            true),
    CLASS_RL(
            144,
            "RL",
            "Restricting access to an area",
            "Fence",
            "",
            true),
    CLASS_S_(
            145,
            "S_",
            "Cover all S codes - Converting a manual operation into a signal for further processing",
            "Influencing\nManually controlling\nSelecting",
            "Control cabinet (control and operate)\nControl panel (operate)\nControl switch\nCordless mouse\nDiscrepancy switch\nKeyboard\nLight pen\nPush-button switch\nPush-button valve Selector switch\nSet-point adjuster",
            true),
    CLASS_SA(
            146,
            "SA",
            "Providing an electrical signal",
            "Control switch, discrepancy switch, keyboard, light pen, pushbutton switch, selector switch, set-point adjuster, switch",
            "",
            true),
    CLASS_SB(
            147,
            "SB",
            "Providing an electromagnetic, optical or acoustical signal",
            "Cordless mouse",
            "",
            true),
    CLASS_SC(
            148,
            "SC",
            "Providing a mechanical signal",
            "Hand wheel, selector switch",
            "",
            true),
    CLASS_SD(
            149,
            "SD",
            "Providing a fluid or pneumatic signal",
            "Push-button valve",
            "",
            true),
    CLASS_T_(
            150,
            "T_",
            "Cover all T codes - Conversion of energy maintaining the type of energy. Conversion of an established signal maintaining the content of information. Conversion of the form or shape of a material",
            "Amplifying\nModulating\nTransforming\nCasting\nCompressing\nConverting\nCutting\nMaterial deforming\nExpanding\nForging\nGrinding\nRolling\nSize enlargement\nSize reduction\nTurning",
            "Antenna\nAmplifier\nCharger\nFrequency convertor\nInterposing transformer\nInverter\nPower supply\nPower transformer\nRectifier\nSignal converter\nTest-value transmitter\nTransducer\nTransformer",
            true),
    CLASS_TA(
            151,
            "TA",
            "Converting electrical energy while retaining the energy type and energy form",
            "DC/DC converter, frequency converter, power transformer, transformer",
            "",
            true),
    CLASS_TB(
            152,
            "TB",
            "Converting electrical energy while retaining the energy type and changing the energy form",
            "Inverter, rectifier",
            "",
            true),
    CLASS_TC(
            153,
            "TC",
            "Converting signals (retention of information content)",
            "Aerial, amplifier, electrical transducer, impulse amplifier, isolating converter, signal converter",
            "",
            true),
    CLASS_TD(
            154,
            "TD",
            "Converting speed of rotation, torque, force into the same kind",
            "Automatic gear, control coupling, fluid amplifier, indexing gear, pressure amplifier, speed convertor, torque converter",
            "",
            true),
    CLASS_TE(
            155,
            "TE",
            "Converting a mechanical form with a machine",
            "Machine tool, saw, shear",
            "",
            true),
    CLASS_TF(
            156,
            "TF",
            "Converting a mechanical form by cold forming (chipless deforming)",
            "Cold drawing equipment, cold rolling equipment, deep drawing equipment",
            "",
            true),
    CLASS_TG(
            157,
            "TG",
            "Converting a mechanical form by hot forming (chipless deforming)",
            "Casting machine, extruder, forging, hot drawing equipment, hot rolling",
            "",
            true),
    CLASS_TH(
            158,
            "TH",
            "Converting radiation energy while retaining energy form",
            "Magnifying glass, parabolic mirror",
            "",
            true),
    CLASS_U_(
            159,
            "U_",
            "Cover all U codes - Keeping objects in a defined position",
            "Bearing\nCarrying\nHolding\nSupporting",
            "Assembly plate\nAssembly rail\nBearings\nBracket\nBuilding foundation\nCabinet\nCable duct\nCable framework\nCable tray\nContainer\nFixture\nGateway\nInsulator\nPipe bridge\nPole\nRoller bearing\nRoom",
            true),
    CLASS_UA(
            160,
            "UA",
            "Holding and supporting electrical energy equipment",
            "Insulator, supporting structure, transformer foundation",
            "",
            true),
    CLASS_UB(
            161,
            "UB",
            "Holding and supporting electrical energy cables and conductors",
            "Cable duct, cable rack, cable tray, cable trough, insulator, mast, portal, post insulator",
            "",
            true),
    CLASS_UC(
            162,
            "UC",
            "Enclosing and supporting electrical energy equipment",
            "Cubicle, encapsulation, housing",
            "",
            true),
    CLASS_UD(
            163,
            "UD",
            "Holding and supporting instruments, control and communication equipment",
            "Printed circuit board, sub-rack, transducer rack",
            "",
            true),
    CLASS_UE(
            164,
            "UE",
            "Holding and supporting instruments, control and communication cables and conductors",
            "Cable rack, duct, shaft",
            "",
            true),
    CLASS_UF(
            165,
            "UF",
            "Enclosing and supporting instrumentation, control and communication equipment",
            "Cabinet, cubicle, enclosures",
            "",
            true),
    CLASS_UG(
            166,
            "UG",
            "Holding and supporting machinery",
            "Machine foundation",
            "",
            true),
    CLASS_UH(
            167,
            "UH",
            "Holding and supporting structural objects",
            "Building foundation, duct (not cable duct, see UG), shaft, structural elements (e.g. column, joist, lintel, suspender beam)",
            "",
            true),
    CLASS_UI(
            168,
            "UI",
            "Holding and supporting piping objects",
            "Bracket for pipes, pipe bridge, pipe hanger",
            "",
            true),
    CLASS_UJ(
            169,
            "UJ",
            "Holding and guiding of shafts and rotors",
            "Ball bearing, roller bearing, sliding bearing",
            "",
            true),
    CLASS_UK(
            170,
            "UK",
            "Holding and guiding objects for manufacturing or erection",
            "Centring device, clamping, fixture",
            "",
            true),
    CLASS_UL(
            171,
            "UL",
            "Fastening and anchoring machinery",
            "Anchor plate, bracket, carrier, erection frame, erection plate",
            "",
            true),
    CLASS_UM(
            172,
            "UM",
            "Spatial objects, housing and supporting other objects",
            "Corridor, duct, hall, passage, room, shaft, stairwell",
            "",
            true),
    CLASS_V_(
            173,
            "V_",
            "Cover all V codes - Processing (treating) of material or products (including preparatory and posttreatment)",
            "Coating\nCleaning\nDehydrating\nDerusting\nDrying\nFiltering\nHeat treatment\nPacking\nPreconditioning\nRecovering\nRe-finishing\nSealing\nSeparating\nSorting\nStirring\nSurface treatment\nWrapping",
            "Separator\nFilter\nInsulator-cleaner\nOil-processing plant",
            true),
    CLASS_VA(
            174,
            "VA",
            "Filling material",
            "Drum, sack, tank car filling equipment",
            "",
            true),
    CLASS_VB(
            175,
            "VB",
            "Packaging product",
            "Packaging machine, palletizer, wrapping machines",
            "",
            true),
    CLASS_VC(
            176,
            "VC",
            "Treating surface",
            "Burnisher, grinding, painting machine, polishing machine",
            "",
            true),
    CLASS_VD(
            177,
            "VD",
            "Free to use",
            "",
            "",
            true),
    CLASS_VE(
            178,
            "VE",
            "Treating material or product",
            "Annealing furnace, balancing machine, blast furnace, melting furnace",
            "",
            true),
    CLASS_VF(
            179,
            "VF",
            "Cleaning material, product or facility",
            "Building cleaning equipment, vacuum cleaner, washing machine,",
            "",
            true),
    CLASS_W_(
            180,
            "W_",
            "Cover all W codes - Guiding or transporting energy, signals, material or products from one place to another",
            "Distributing\nGuiding\nLeading\nPositioning\nTransporting",
            "Busbar\nBushing Cable\nConductor Crane\nData bus\nOil-pipeline\nOptical fiber\nPipe\nSub-distribution board",
            true),
    CLASS_WA(
            181,
            "WA",
            "Distributing high voltage electrical energy (> 1 000 V AC or > 1 500 V DC.)",
            "Busbar",
            "",
            true),
    CLASS_WB(
            182,
            "WB",
            "Transporting high voltage electrical energy (> 1 000 V AC or > 1 500 V DC.)",
            "Bushing, cable, conductor",
            "",
            true),
    CLASS_WC(
            183,
            "WC",
            "Distributing low voltage electrical energy (≤ 1 000 V AC or ≤ 1 500 V DC)",
            "Busbar, motor control center, switchgear assembly",
            "",
            true),
    CLASS_WD(
            184,
            "WD",
            "Transporting low voltage electrical energy (≤ 1 000 V AC or ≤ 1 500 V DC)",
            "Bushing, cable, conductor",
            "",
            true),
    CLASS_WE(
            185,
            "WE",
            "Conducting earth potential or reference potential",
            "Bonding conductor, earthing busbar, earthing conductor, earth rod, shield bus",
            "",
            true),
    CLASS_WF(
            186,
            "WF",
            "Distributing electrical or electronic signal",
            "Data bus, field bus",
            "",
            true),
    CLASS_WG(
            187,
            "WG",
            "Transporting electrical or electronic signal",
            "Control cable, data line, measuring cable",
            "",
            true),
    CLASS_WH(
            188,
            "WH",
            "Transporting and routing optical signal",
            "Optical fiber, optical fiber cable, optical wave guide",
            "",
            true),
    CLASS_WI(
            189,
            "WI",
            "Transporting material or product (not driven)",
            "Conductor, inclined plane, roller table",
            "",
            true),
    CLASS_WJ(
            190,
            "WJ",
            "Conducting or guiding flow of substance in open enclosure",
            "Channel",
            "",
            true),
    CLASS_WK(
            191,
            "WK",
            "Conducting or guiding flow of substance in flexible, closed enclosure",
            "Hose",
            "",
            true),
    CLASS_WL(
            192,
            "WL",
            "Conducting or guiding flow of substance in rigid, closed enclosure",
            "Air duct, pipe, stack",
            "",
            true),
    CLASS_WM(
            193,
            "WM",
            "Transporting mechanical energy",
            "Chain, linkage, rotor, shaft, V-belt",
            "",
            true),
    CLASS_WN(
            194,
            "WN",
            "Conducting or guiding track-bound transport equipment",
            "Points, rails, railway, turntable",
            "",
            true),
    CLASS_WO(
            195,
            "WO",
            "Conducting or guiding persons (access equipment)",
            "Catwalk, platform, stair",
            "",
            true),
    CLASS_WP(
            196,
            "WP",
            "Conducting or guiding mobile transport equipment",
            "Path, road, shipping routes",
            "",
            true),
    CLASS_X_(
            197,
            "X_",
            "Cover all X codes - Connecting objects",
            "Connecting\nCoupling\nJoining",
            "Connector\nConverter-terminal box\nMarshalling racks\nPiping flange\nPlug connector\nSocket\nTerminal\nTerminal block\nTerminal strip",
            true),
    CLASS_XA(
            198,
            "XA",
            "Connecting high voltage objects (> 1 000 V AC or > 1 500 V DC)",
            "Terminal, junction box, socket, bushing, cable sealing box",
            "",
            true),
    CLASS_XB(
            199,
            "XB",
            "Connecting low voltage objects (≤ 1 000 V AC or ≤ 1 500 V DC)",
            "Connector, junction box, plug connector, socket-outlet, terminal, terminal block, terminal strip, cable sealing box",
            "",
            true),
    CLASS_XC(
            200,
            "XC",
            "Connecting to earth potential or reference potential",
            "Bonding terminal, earthing terminal, shield connection terminal",
            "",
            true),
    CLASS_XD(
            201,
            "XD",
            "Connecting data network carriers",
            "Hub",
            "",
            true),
    CLASS_XE(
            202,
            "XE",
            "Connecting data network carriers",
            "Connection element, plug connector, signal distributor, terminal, terminal block",
            "",
            true),
    CLASS_XF(
            203,
            "XF",
            "Connecting optical signal carriers",
            "Optical connection",
            "",
            true),
    CLASS_XG(
            204,
            "XG",
            "Connecting rigid enclosures for flows of substances",
            "Piping fitting, piping flange, piping coupling",
            "",
            true),
    CLASS_XH(
            205,
            "XH",
            "Connecting flexible enclosures for flows of substances",
            "Hose connection, hose coupling",
            "",
            true),
    CLASS_XI(
            206,
            "XI",
            "Connecting objects for transport of mechanical energy, non-detachable",
            "Rigid coupling",
            "",
            true),
    CLASS_XJ(
            207,
            "XJ",
            "Connecting objects for transport of mechanical energy, detachable",
            "Control coupling, disengaging coupling",
            "",
            true),
    CLASS_XK(
            208,
            "XK",
            "Connecting irreversible connected objects",
            "Bonded connection, soldered connection, welded connection",
            "",
            true),
    CLASS_XL(
            209,
            "XL",
            "Connecting reversible connected objects",
            "Hook, lug",
            "",
            true),
    CLASS_Y_(
            210,
            "Y_",
            "Cover all Y codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_YA(
            211,
            "YA",
            "Free to use",
            "",
            "",
            true),
    CLASS_YB(
            212,
            "YB",
            "Free to use",
            "",
            "",
            true),
    CLASS_Z_(
            213,
            "Z_",
            "Cover all Z codes - Customer specific codes",
            "",
            "",
            true),
    CLASS_ZA(
            214,
            "ZA",
            "Free to use",
            "",
            "",
            true),
    CLASS_ZB(
            215,
            "ZB",
            "Free to use",
            "",
            "",
            true),
    INVALID_CLASS(
            -1,
            "??",
            "Invalid Classification",
            "No example",
            "",
            false);

    private final int classId;
    private final String code;
    private final String codeDescription;
    private final String codeExample;
    private final String codeUsageExample;
    private final boolean active;

    ClassificationType(int classId, String code, String codeDescription, String codeExample, String codeUsageExample, boolean active) {
        this.classId = classId;
        this.code = code;
        this.codeDescription = codeDescription;
        this.codeExample = codeExample;
        this.codeUsageExample = codeUsageExample;
        this.active = active;
    }

    public int getClassId() {
        return classId;
    }

    public String getCode() {
        return code;
    }

    public String getCodeDescription() {
        return codeDescription;
    }

    public String getCodeExample() {
        return codeExample;
    }

    public String getCodeUsageExample() {
        return codeUsageExample;
    }

    public boolean isActive() {
        return active;
    }

    public static ClassificationType valueOf(int value) {
        for (ClassificationType entityDataElement : ClassificationType.values()) {
            if (entityDataElement.classId == value) return entityDataElement;
        }
        return INVALID_CLASS;
    }
}
