IF OBJECT_ID(N'[dbo].[USER_PREFERENCE]', N'U') IS NULL
BEGIN
CREATE TABLE [dbo].[USER_PREFERENCE] (
    [UserId] INT NOT NULL,
    [Preferences] XML NOT NULL
        CONSTRAINT [DF_USER_PREFERENCE_Preferences]
        DEFAULT CONVERT(XML, N'<UserPreferences />'),
    [ChangedAt] DATETIME2(0) NOT NULL
        CONSTRAINT [DF_USER_PREFERENCE_ChangedAt]
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT [PK_USER_PREFERENCE]
        PRIMARY KEY CLUSTERED ([UserId] ASC),

    CONSTRAINT [FK_USER_PREFERENCE_USERS]
        FOREIGN KEY ([UserId]) REFERENCES [dbo].[USERS] ([UserId])
);
END;
GO
