IF OBJECT_ID(N'[dbo].[USER_PASSWORD_RESET_TOKEN]', N'U') IS NULL
BEGIN
CREATE TABLE [dbo].[USER_PASSWORD_RESET_TOKEN] (
    [TokenId] INT IDENTITY(1,1) NOT NULL,

    [UserId] INT NOT NULL,
    [TokenHash] NVARCHAR(255) NOT NULL,

    [ExpiresAt] DATETIME2(0) NOT NULL,
    [UsedAt] DATETIME2(0) NULL,

    [CreatedAt] DATETIME2(0) NOT NULL
        CONSTRAINT [DF_USER_PASSWORD_RESET_TOKEN_CreatedAt] DEFAULT SYSUTCDATETIME(),

    [CreatedByUserId] INT NULL,

    CONSTRAINT [PK_USER_PASSWORD_RESET_TOKEN]
        PRIMARY KEY CLUSTERED ([TokenId] ASC),

    CONSTRAINT [UQ_USER_PASSWORD_RESET_TOKEN_TokenHash]
        UNIQUE ([TokenHash])
    );
END;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'IX_USER_PASSWORD_RESET_TOKEN_UserId'
      AND object_id = OBJECT_ID(N'[dbo].[USER_PASSWORD_RESET_TOKEN]')
)
BEGIN
CREATE INDEX [IX_USER_PASSWORD_RESET_TOKEN_UserId]
    ON [dbo].[USER_PASSWORD_RESET_TOKEN] ([UserId], [UsedAt], [ExpiresAt]);
END;
GO
